AEVI-AppFlow/pos-android-sdk

- build.gradle
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/config/FpsSettings.java
> Add new setting for status bar access

- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/PaymentServiceInfoProvider.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/ui/PaymentResponseBuilderActivity.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/util/IdProvider.java
- build.gradle
- dependencies.gradle
Demostrates how a PA should set the transaction references for merchant and terminal Id
> Added example code to PaymentServiceProvider

- .circleci/config.yml
- artifacts.gradle
- publish-repo-android.gradle
Update to push samples to repo so they can be added to developer archive
> Release 1.1.3

- build.gradle
- dist.gradle
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseServiceInfoProvider.java
- payment-flow-service-api/build.gradle
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/model/AmountsModifier.java
- payment-initiation-api/build.gradle
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/PaymentApi.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Basket.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentBuilder.java
Now reduced to two single javadocs where the main APIs are merged with the flow base one
> Refactored javadocs structure

- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/PaymentClient.java
> Removed duplicate sentance

- flow-base-api/src/main/java/com/aevi/sdk/flow/model/config/FpsSettings.java
> Add new legacy support flag to FpsSettings

- flow-base-api/src/main/java/com/aevi/sdk/flow/model/InternalData.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseApiService.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseListenerService.java
Remove componentName from internalData
> Ensure packageName is always set in internalData

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/adapter/SystemOverviewAdapter.java
- PaymentInitiationSample/src/main/res/values/strings.xml
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseApiService.java
> System overview fixes

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/GenericResultActivity.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/PaymentInitiationActivity.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/PaymentResultActivity.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/FlowServicesFragment.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/SystemOverviewFragment.java
- PaymentInitiationSample/src/main/res/layout/activity_generic_result.xml
- PaymentInitiationSample/src/main/res/layout/activity_payment_approved.xml
- PaymentInitiationSample/src/main/res/layout/activity_payment_error.xml
- PaymentInitiationSample/src/main/res/layout/fragment_payment.xml
- dependencies.gradle
- sample-commons/src/main/java/com/aevi/sdk/pos/flow/sample/ui/BaseSampleAppCompatActivity.java
Orientation fix for Payment Initiation App closes SDKNEW-873 SDKNEW-878
Override back button in samples closes SDKNEW-880
Update rxmess to RC3 fixes websocket close issues
Added close button to POS result screens closes SDKNEW-877
Prevent back button in sample flow service and payment service apps close SDKNEW-874 SDKNEW-880
Minor layout improves
> Minor fixes

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/GenericRequestFragment.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/PaymentFragment.java
> Handle busy

- FlowServiceSample/src/main/res/values/integers.xml
- FlowServiceSample/src/main/res/values/strings.xml
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/model/SplitRequest.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/model/TransactionResponseBuilder.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/PreTransactionModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/SplitModel.java
- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/model/SplitRequestTest.java
- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/stage/SplitModelTest.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Amounts.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Basket.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/BasketItem.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentResponse.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Transaction.java
- payment-initiation-api/src/test/java/com/aevi/sdk/pos/flow/model/AmountsTest.java
- sample-commons/src/test/java/com.aevi.sdk.pos.flow.sample/SplitBasketHelperTest.java
- Stricter rules for payment augmentations
- New fields to track the total request amounts as updated from the flow
- Added tax info to javadocs
- Minor other updates
> Various updates to models and javadocs

- sample-commons/src/main/java/com/aevi/sdk/pos/flow/sample/ui/ModelDetailsFragment.java
- sample-commons/src/main/java/com/aevi/sdk/pos/flow/sample/ui/TransactionSection.java
> Fix for crash related to displaying transaction responses

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/model/ApiFunction.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/model/SampleContext.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/PopupActivity.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/adapter/PaymentResponsesAdapter.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/ApiFunctionsFragment.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/PaymentResponsesFragment.java
- PaymentInitiationSample/src/main/res/values/strings.xml
- flow-base-api/src/main/java/com/aevi/sdk/flow/BaseApiClient.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/constants/AppMessageTypes.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/ResponseQuery.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/ResponseQueryBuilder.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/PaymentClient.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/PaymentClientImpl.java
Allows responses to be queried for all domains
> Add API to query for responses

- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/model/TransactionResponseBuilderTest.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Transaction.java
Ensure that partial auth info is available if requested in verbose JSON
> Add partial auth info

- FlowServiceSample/src/main/java/com/aevi/sdk/pos/flow/flowservicesample/service/GenericRequestService.java
- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/GenericRequestFragment.java
- PaymentInitiationSample/src/main/res/layout/fragment_generic_request.xml
- PaymentInitiationSample/src/main/res/values/strings.xml
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/GenericStageHandler.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/Request.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/config/FlowConfig.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/config/FlowConfigBuilder.java
- flow-base-api/src/test/java/com/aevi/sdk/flow/model/config/FlowConfigTest.java
- sample-commons/src/main/java/com/aevi/sdk/pos/flow/sample/ui/ModelDetailsFragment.java
- sample-commons/src/main/res/values/strings.xml
Can be specified via FlowConfig or Request
> Added support for generic background flows

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/GenericRequestFragment.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/GenericStageHandler.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/ui/TransactionProcessingActivity.java
- build.gradle
Fix the way references are handled for reversal and receipt delivery
> Fix up sample to match documentation

- PaymentInitiationSample/src/main/java/com/aevi/sdk/pos/flow/paymentinitiationsample/ui/fragment/GenericRequestFragment.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/GenericStageHandler.java
- PaymentServiceSample/src/main/java/com/aevi/sdk/pos/flow/paymentservicesample/ui/TransactionProcessingActivity.java
- build.gradle
Fix up sample to match documentation
Fix the way references are handled for reversal and receipt delivery
Fixed potential NPE
Commits cherry picked from release/2.0.1
> Read internal id and ensure match on reversal

- build.gradle
- flow-base-api/src/main/java/com/aevi/sdk/flow/constants/InternalDataKeys.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseApiService.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseGenericService.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BasePostGenericService.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/service/BaseStatusUpdateService.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/ActivityComponentDelegate.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/AndroidComponentDelegate.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/BaseStageModel.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/GenericStageModel.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/PostGenericStageModel.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/ServiceComponentDelegate.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/stage/StatusUpdateModel.java
- flow-base-api/src/test/java/com/aevi/sdk/flow/stage/ServiceComponentDelegateTest.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/service/ActivityProxyService.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/service/BasePaymentFlowService.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/CardReadingModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/PostFlowModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/PostTransactionModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/PreFlowModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/PreTransactionModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/SplitModel.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/stage/TransactionProcessingModel.java
- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/stage/PreTransactionModelTest.java
- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/stage/SplitModelTest.java
Provide method to obtain flow initiation package name
> Pass initator internaldata into all stage models

- payment-flow-service-api/src/test/java/com/aevi/sdk/pos/flow/stage/PreTransactionModelTest.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Payment.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentBuilder.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/TransactionRequest.java
- Enables FPS filtering of payment apps based on method
- Allows a PA to have a method pre-selected
> Added payment method to payments / transactions

- build.gradle
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Basket.java
> Rounding bug

- .circleci/config.yml
Changes `store` map to list and merges with `steps` list.
> Fix CircileCI config duplicate store_artifacts

- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentBuilder.java
- payment-initiation-api/src/test/java/com/aevi/sdk/pos/flow/model/PaymentBuilderTest.java
Add new withAdditionalData method
Closes #SDKNEW-1206
> Deprecate addAdditionalData(AdditionalData ad) on PaymentBuilder

- flow-base-api/src/main/java/com/aevi/sdk/flow/model/BaseIdNameEntity.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/BaseModel.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/Customer.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/Request.java
- flow-base-api/src/main/java/com/aevi/sdk/flow/model/Response.java
- payment-flow-service-api/src/main/java/com/aevi/sdk/pos/flow/model/SplitRequest.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Basket.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Payment.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentFlowServiceInfo.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/PaymentResponse.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/Transaction.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/TransactionRequest.java
- payment-initiation-api/src/main/java/com/aevi/sdk/pos/flow/model/TransactionResponse.java
- payment-initiation-api/src/test/java/com/aevi/sdk/pos/flow/model/BasketTest.java
- payment-initiation-api/src/test/java/com/aevi/sdk/pos/flow/model/PaymentTest.java
- payment-initiation-api/src/test/java/com/aevi/sdk/pos/flow/model/TransactionTest.java
Allows a check to see if all data is the same except for ids
> Add equivalence methods to all objects
